variable "target_node" {}
variable "cores" {}
variable "memory" {}
variable "hostname" {}
variable "password" {}
variable "network_name" {}
variable "network_bridge" {}
variable "network_ip" {}
variable "start" {}
variable "ostemplate" {}
variable "rootfs_storage" {}
variable "rootfs_size" {}
